### ISSUE TITLE
"Unable to determine PyArg_Parse format for size_t"

### ISSUE THREAD

**Issue by Angeloss** [jelmer/subvertpy#33]
I setup SVN_DEV, SVN_BDB, SVN_LIBINTL.
I have Mercurial installed.
I have C++ For Python
But when I `Pip install subvertpy` I got this error:

```
 creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\subvertpy
    C:\Users\Angeloss\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32 -I. -I. -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include\apr -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include\apr-util -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include\apr-iconv -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include -Isubvertpy -Ic:\python27\include -Ic:\python27\PC /Tcsubvertpy\client.c /Fobuild\temp.win-amd64-2.7\Release\subvertpy\client.obj
    client.c
    subvertpy\client.c(101) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    subvertpy\client.c(2032) : warning C4244: 'function' : conversion from 'svn_filesize_t' to 'long', possible loss of data
    C:\Users\Angeloss\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32 -I. -I. -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include\apr -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include\apr-util -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include\apr-iconv -IC:\Users\Angeloss\Downloads\svnwin\svn-win32-1.8.17\include -Isubvertpy -Ic:\python27\include -Ic:\python27\PC /Tcsubvertpy\editor.c /Fobuild\temp.win-amd64-2.7\Release\subvertpy\editor.obj
    editor.c
    subvertpy\editor.c(84) : fatal error C1189: #error :  "Unable to determine PyArg_Parse format for size_t"
    error: command 'C:\\Users\\Angeloss\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\angeloss\\appdata\\local\\temp\\pip-install-vo5_rr\\subvertpy\\setup.py'"'"'; __file__='"'"'c:\\users\\angeloss\\appdata\\local\\temp\\pip-install-vo5_rr\\subvertpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\angeloss\appdata\local\temp\pip-record-dp7trp\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

Do you know how can I complete the installation of subvertpy? It is a dependency to hgsubversion to build a TortoiseHG Installer.

Thank you.

**Comment by jelmer** [comment]
We cam possibly get rid of that check if we eliminate the remaining size_t -> long assumptions.

Can you try building from master ("pip install git+https://github.com/jelmer/subvertpy") and pasting the output here?

**Comment by Angeloss** [comment]
This is the output:

```
ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\angeloss\\appdata\\local\\temp\\pip-req-build-h_nosi\\setup.py'"'"'; __file__='"'"'c:\\users\\angeloss\\appdata\\local\\temp\\pip-req-build-h_nosi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: c:\users\angeloss\appdata\local\temp\pip-req-build-h_nosi\
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\angeloss\appdata\local\temp\pip-req-build-h_nosi\setup.py", line 167, in <module>
        (apr_includedir, apr_link_flags) = apr_build_data()
      File "c:\users\angeloss\appdata\local\temp\pip-req-build-h_nosi\setup.py", line 86, in apr_build_data
        includedir = apr_config("--includedir")
      File "c:\users\angeloss\appdata\local\temp\pip-req-build-h_nosi\setup.py", line 71, in apr_config
        return config_value("apr-1-config", arg)
      File "c:\users\angeloss\appdata\local\temp\pip-req-build-h_nosi\setup.py", line 59, in config_value
        return run_cmd(cmd, arg)
      File "c:\users\angeloss\appdata\local\temp\pip-req-build-h_nosi\setup.py", line 39, in run_cmd
        if os.WIFEXITED(status):
    AttributeError: 'module' object has no attribute 'WIFEXITED'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Thank you very much for your kick response. Very appreciated.

**Comment by Angeloss** [comment]
oh I see, there is no os.WIFEXITED() function on windows. From the official python documentation:

s.WIFEXITED(status)
Return True if the process exited using the exit(2) system call, otherwise return False.
**Availability: Unix.**

How could I make it work if I'm on Windows?

**Comment by jelmer** [comment]
I've pushed a fix to master that removes WIFEXITED.

**Comment by Angeloss** [comment]
Thank you very much! I no longer get the WIFEXITED error. 
But now setup now is looking for a `apr-1-config`.
I suppose I need to download and Build APR for windows and set an Environment Variable named APR_CONFIG pointing to this build. Is just a guess, I'm not an python expert, I'll let you know how it goes.
Thank you very much for you support.

**Comment by jelmer** [comment]
If you already have subversion installed, you should also have apr-config installed somehow.

**Comment by Angeloss** [comment]
I did install subversion 1.8.17 with the MSI from here: https://sourceforge.net/projects/win32svn/files/1.8.17/apache22/
But I can't find apr-1-config, should I Build subversion or Apache?

**Comment by jelmer** [comment]
I'm not sure unfortunately, I have limited experience building on Windows. You would need a version of apr that matches what your subversion was build with.

The official build instructions for subversion are at https://svn.apache.org/repos/asf/subversion/trunk/INSTALL, but they're quite tedious.

**Comment by jelmer** [comment]
This should be fixed now.

subvertpy now builds on Windows - see the github action for details. I don't have any packages published yet, but that's a possibility.
