### ISSUE TITLE
Homepage urls not updated in PyPI and Readme.md

### ISSUE THREAD

**Issue by stefanlada** [jelmer/subvertpy#36]
The URLs leading to the projects homepage on PyPI (https://pypi.org/project/subvertpy/) and in your GitHub Readme.md point to an unreachable location (https://jelmer.uk/subvertpy/).

It seems they were forgotten wenn updating the url paths.

**Comment by jelmer** [comment]
The URL is now https://jelmer.uk/code/subvertpy/; I'll add a redirect

**Comment by lovezyz** [comment]
I can't install subvertpy.
python .\setup.py
Traceback (most recent call last):
  File "D:\proj_ns\Review\reviewboard\subvertpy-0.11.0\setup.py", line 42, in apr_build_data
    includedir = os.environ['APR_INCLUDE_DIR']
  File "D:\python\version\3.10.9\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'APR_INCLUDE_DIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\proj_ns\Review\reviewboard\subvertpy-0.11.0\setup.py", line 22, in config_value
    return subprocess.check_output([command] + args).strip().decode()
  File "D:\python\version\3.10.9\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\python\version\3.10.9\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\python\version\3.10.9\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\python\version\3.10.9\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\proj_ns\Review\reviewboard\subvertpy-0.11.0\setup.py", line 139, in <module>
    (apr_includedir, apr_link_flags) = apr_build_data()
  File "D:\proj_ns\Review\reviewboard\subvertpy-0.11.0\setup.py", line 45, in apr_build_data
    includedir = apr_config(["--includedir"])
  File "D:\proj_ns\Review\reviewboard\subvertpy-0.11.0\setup.py", line 32, in apr_config
    return config_value("apr-1-config", "APR_CONFIG", args)
  File "D:\proj_ns\Review\reviewboard\subvertpy-0.11.0\setup.py", line 25, in config_value
    raise Exception(
Exception: apr-1-config not found. Please set APR_CONFIG environment variable
